# -*- coding: utf-8 -*-
"""COVID_19 CASE STUDY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zqBbQQgHTBhAAMfzI28rlYU66cZCA66Q
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

df ="https://raw.githubusercontent.com/datasets/covid-19/master/data/countries-aggregated.csv"
df = pd.read_csv(df)
df

df.head()

df.info()

df.shape

df.describe()

df.isnull().sum()

df.tail()

df.size

"""Data Preprocessing"""

df = df[df.Confirmed > 0]
df.head()

df.info()

df.head()

df[df.Country == "India"]

fig = px.choropleth(df, locations="Country", locationmode='country names', color="Confirmed", hover_name="Country", animation_frame="Date")
fig.show()

fig = px.choropleth(df, locations="Country", locationmode='country names', color="Deaths", hover_name="Country", animation_frame="Date")
fig.show()

df_india = df[df.Country == "India"]
df_india.head()

df_india=df_india[["Date","Confirmed"]]
df_india.head()

df_india['Infections'] = df_india['Confirmed'].diff()
df_india.head()

px.line(df_india, x="Date", y="Infections")

px.line(df_india, x="Date", y="Confirmed")

df.head()

countries = list(df.Country.unique())

max_infection_rate = []
for c in countries:
  MIR = df[df.Country == c]["Confirmed"].diff().max()
  max_infection_rate.append(MIR)
print(max_infection_rate)

df_MIR = pd.DataFrame()

df_MIR["Country"] = countries
df_MIR["Max Infection Rate"] = max_infection_rate
df_MIR.head()

px.bar(df_MIR, x = "Country", y = "Max Infection Rate",log_y = True)

india_LD1 ='2020-03-24'
india_LD2 ='2020-06-24'
india_LD3 ='2020-09-24'
india_LD4 ='2020-12-24'

df_india = df[df.Country == "India"]
df_india.head()

df_india = df_india[["Date","Confirmed"]]
df_india.head()

df_india['Infections'] = df_india['Confirmed'].diff()
df_india.head()

fig = px.line(df_india, x="Date", y="Infections")

fig.add_shape(
    dict(
        type = "line",
        x0 = india_LD1,
        y0 = 0,
        x1 = india_LD1,
        y1 = df_india["Infections"].max(),
        line = dict(color = "red", width = 2)
    )
)
fig.add_shape(
    dict(
        type = "line",
        x0 = india_LD2,
        x1 = india_LD2,
        y0 = 0,
        y1 = df_india["Infections"].max(),
        line = dict(color = "red", width = 2)
    )
)
fig.add_shape(
    dict(
        type = "line",
        x0 = india_LD3,
        x1 = india_LD3,
        y0 = 0,
        y1 = df_india["Infections"].max(),
        line = dict(color = "red", width = 2)
    )
)
fig.add_shape(
    dict(
        type = "line",
        x0 = india_LD4,
        x1 = india_LD4,
        y0 = 0,
        y1 = df_india.Infections.max(),
        line = dict(color = "red", width = 2)
    )
)
fig.show()



